server:
  port: 8088
spring:
  datasource:
    password: 123qweasdzxc
    username: securetrack_user
    url: jdbc:postgresql://localhost:5432/securetrack_db
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: google
            scope:
              - email
              - profile
