server:
  port: 8088
spring:
  datasource:
    password: 123qweasdzxc
    username: securetrack_user
    url: jdbc:postgresql://localhost:5432/securetrack_db
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      port: 6379
      host: localhost
      password:
      database: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: google
            scope:
              - email
              - profile
logging:
  level:
    org.hibernate.orm.connections.pooling: ERROR
jwt:
  token:
    validity: 18000
    authorities:
      key: roles
    token-prefix: Bearer
    header-string: Authorization

access:
    secret:
      key: ApeVFjUOyTmk7XYwgcYwIEsix1mALAsQhftYQqWHE8P6kcnqbZv0Uxj9HduKEvjXzz0sVYCG0ZjSBtmxadtAiQ==
refresh:
    secret:
      key: YDpL6EWoHzS6Zk2QhQpK3ZMVxvAg0LmxyDOolbqVJo6nVUWhq45jj3k2q6T9xXAlPtw9uC5P54rcGb0uBoP3tg==

springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true
    path: /v3/api-docs
virustotal:
  api:
   key: "5d3eb223bebcdbc022a55472cec9269a8fee2021efad152a728267e1bce7d420"